CREATE OR REPLACE TRIGGER check_cars_sold
    Before INSERT OR UPDATE
    ON SALES
    FOR EACH ROW
DECLARE
    sold NUMBER(1);
BEGIN
    SELECT CARS.sold INTO sold FROM CARS WHERE ID = :new.CARS_ID;
    IF sold = 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Car is already sold');
    END IF;
END;


CREATE OR REPLACE TRIGGER update_sold_cars
    AFTER INSERT OR UPDATE
    ON SALES
    FOR EACH ROW
BEGIN
    UPDATE CARS SET sold = 1 WHERE ID = :new.CARS_ID;
END;

BEGIN
    INSERT INTO SALES (CARS_ID, CLIENTS_ID, DATE_OF_SALE, EMPLOYEES_ID)
    VALUES (6, 1, TO_DATE('2019-01-01', 'YYYY-MM-DD'), 1);
END;

SELECT *
FROM SALES;
DELETE
FROM SALES
WHERE ID = 23;

UPDATE CARS SET SOLD = 1 where ID IN (1, 2, 4, 5, 7, 8, 10) ;
SELECT * from CARS